### ISSUE TITLE
move error level under plv8 object

### ISSUE THREAD

**Issue by niquola** [plv8/plv8#128]
I'm working on translating node code into plv8 procs (moking plv8 in node) and global enum for error levels looks inaccurate :)

Is it possible to create aliases in plv8 - ```plv8.elog(plv8.NOTICE)``` - so the only global object be plv8?
Is it difficult to support more idiomatic for js people `console.[log,error,dir]`?

**Comment by JerrySievert** [comment]
@niquola it's actually not that difficult to set up your own via a startup proc:

https://github.com/plv8/plv8/blob/master/doc/plv8.md#start-up-procedure

this should work for local environments, but will not work if you are releasing for other users.

**Comment by niquola** [comment]
yes, that's the problem
i'm going reuse npm infrastructure to distribute modules for plv8
The idea is to give the possibility run almost the same code in node and in plv8.
So you can develop & test in node and then deploy to postgres.

But if you think, this is too cosmetic - i'll close the issue :)

**Comment by JerrySievert** [comment]
@niquola not my project, just added a couple of cents :)

i've written a couple of shims that make moving between node and plv8 a little easier, including some testing, but nothing that i've seen officially in plv8 itself.

**Comment by niquola** [comment]
@JerrySievert what shims? could you share them?

**Comment by JerrySievert** [comment]
there are some here: https://github.com/JerrySievert/mongolike

but some of it is private ip that i can't share - i can see about breaking some of it out.

**Comment by bendiy** [comment]
@niquola I've been playing around with https://github.com/clkao/plv8x to push npm modules into Postgres. It doesn't quite do what I need because of the way it browserify's the package. Is this what your https://github.com/niquola/plpl repo is for?

I've been able to polyfill `require` and `console` using `SET plv8.start_proc...`. It would be nice if there was a more generic way to initialize the plv8 environment that didn't require the user changing the config.

One idea I've been considering is using [Postgres' Large Objects](http://www.postgresql.org/docs/9.4/static/largeobjects.html) support to import `postgresql.conf`, set `plv8.start_proc` and export `postgresql.conf` back to the file system. That is something you can do by running a few queries with `node-postgres` from the Node.js side.

**Comment by JerrySievert** [comment]
@bendiy i think what you're looking for is an unsecure version of plv8 (which doesn't actually exist yet).  i've been down this road :)

i didn't end up forking for an unsecure version, but now might be the right time.  unsecure adds filesystem access, as well as other things that allow access into the database by a normal user (sockets, etc).

this would allow for a direct _require_, which is probably what you are looking for in the end.

this means that by default, plv8 wouldn't support it, but gives options for external access otherwise.  postgres supports this functionality.

**Comment by bendiy** [comment]
@JerrySievert Yes, an untrusted version of plv8 would be an option, but I don't think I need it. 

I'm mainly looking to write universal javascript code that can run in Node.js and plv8. That code would just be doing queries against the database. Wrapping `pg.query` and `plv8.exec` in a generic `query` handler that does environment detection. I don't need filesystem or socket access (yet). My Postgres Large Object idea is just a work around to get `plv8.start_proc` set from userland without `sudo`.

It would be interesting to see a generic library that polyfills _most_ of the basic Node.js functions (`require`, `console`, etc.) so npm packages, that don't warrant an untrusted version, would work in plv8. Plv8x supports some of this (`require`), but not all (`console`, etc.).

**Comment by niquola** [comment]
@bendiy yes, that's what I want with plpl. I've switched to start_proc too and caching modules in global object. You could set init function on connection start (not only in config) - SET plv8.start_proc = 'plv8_init';

**Comment by bendiy** [comment]
`SET plv8.start_proc = 'plv8_init';` doesn't work for my use case because random end users might be doing something with `psql` or `pgAdmin` on the database directly (silly users :smile:). The `postgresql.conf` is the only way to ensure all users have the same inited plv8 environment.

I'll keep an eye on `plpl` for when I circle back to this task.

**Comment by JerrySievert** [comment]
i'm going to go ahead and close this issue.
