### ISSUE TITLE
v1.4.8 compile fails on FreeBSD 9.3; unrecognized command line option "-std=c++11"

### ISSUE THREAD

**Issue by msqr** [plv8/plv8#182]
I am trying to update my plv8js package on a FreeBSD 9.3 system from v1.4.4 to v1.4.8, but the compilation fails with:

`c++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I. -I/usr/local/include/postgresql/server -I/usr/local/include/postgresql/internal -I/usr/local/include -I/usr/local/include -fPIC -c -o plv8_param.o plv8_param.cc
cc1plus: error: unrecognized command line option "-std=c++11"`

I noticed there are failure messages generated on the freebsd-pkg-fallout list as well, e.g.

https://www.mail-archive.com/freebsd-pkg-fallout@freebsd.org/msg283743.html

Is there a work-around to get this package to compile successfully?

**Comment by nbering** [comment]
Probably not a coincidence that `1.4.4` is the most recent version that I managed to build on Ubuntu as well, and that there was nearly a year gap between `1.4.4` and the more recent versions. I'm not sure off the top of my head if the error messages I got were the same.

At first I thought it was related to #158, but if #176 should I should still be able to use v8 3.14 with all `1.4.x` versions.

**Comment by JerrySievert** [comment]
it appears that your version of `g++` is old enough to not support c++11.

there are a couple of workarounds possible:

1) upgrade g++ to 4.8
2) try https://github.com/plv8/plv8/blob/master/Makefile#L59-L60 (that note is in the 1.5+ and master branches)

@nbering you are correct, the 1.4.* releases will continue to work with 3.14, we've backported bug fixes and a small amount of functionality in order to help the distro's that have not been able to update v8 versions, but in 1.5 we moved to a higher v8 version that breaks compatibility, and 2.0 moves even further, but gains us parity with node.  this should help in the future, as well as gains us a lot of es6 capabilities.

**Comment by msqr** [comment]
Thanks for the tips; I was compiling with the system compiler, which is gcc 4.2.1. I switched to using the system version of clang (3.4.1) and that was able to compile without modifying the Makefile.

I think the maintainer of the FreeBSD port might need to make a tweak to the port, but for this ticket I've been able to work around the problem.

Thanks again!
