### ISSUE TITLE
Binaries for PostgreSQL 9.5/9.6 (Windows)

### ISSUE THREAD

**Issue by devIceMan** [plv8/plv8#200]
Hi! Excuse me for my arrogance, but could someone please build latest version of plv8 (1.5) ?
I apologize for any inconvenience this may cause but could you please build this as I can't handle that myself. Any help or directions will be much appreciated. Thank you in advance!

**Comment by JerrySievert** [comment]
Regina Ore (@robe2) maintains windows builds for plv8 1.4.8:  http://www.postgresonline.com/journal/archives/367-PLV8-binaries-for-PostgreSQL-9.6beta1-windows-both-32-bit-and-64-bit.html

there are also some note there on compiling.  the plv8 project itself does not maintain binary builds for any platform, but we work with OS maintainers to make sure they have a way to distribute.

**Comment by robe2** [comment]
@devIceMan    I  haven't had a chance to revisit compiling v8 newer engine and that's always the tricky part for building with  PL/V8.  The 9.6 build I did was for 1.4.8 which works fine on 9.6.0 and 9.6.1.

The plv8 1.5 requires a newer v8 than what I have built.  So unfortunately I can't do that so easily yet and may take me some time.

Once I do I'll post back to this ticket and instructions on how to compile as well unless someone beats me to it.

**Comment by devIceMan** [comment]
@robe2 Thank you for the answer. Thus the only we can do is wait )))

**Comment by robe2** [comment]
Yah sadly I gave it a check to try to compile newer V8.  No success yet under mingw64 (which is the chain I use for compiling) and I'm not adept enough at VS to even bother with that.  

What's even more annoying is they keep on changing the supported chains.  Earlier in the 3.14 days Scons was supported, which is what I used to compile with and worked.  Then they moved to Gyp which I had no success after downloading all these depot_tools etc. with (though I thought I was close) and now they are saying they are deprecating Gyp for GN. https://github.com/v8/v8/wiki/Building%20with%20Gyp (which GN as far as I can tell, seems like still a half-baked idea). 

They have something called ninja too - have no idea what that is.

So I might wait it out a little till they have their GN more baked.  When I try it, it just sends me to some page about building on windows which gives me a 404.

Anyway I'll keep this ticket open.  We should probably change the title though, since it's really binaries for

PLV8 1.5+ we are talking about.  PLV8 1.4.8 I have binaries for and can continue to provide for PLV8 1.4 releases and can even for PostgreSQL 10 when comes out.

**Comment by JerrySievert** [comment]
Thanks for trying, Regina, if it's any consolation, 1.5 doesn't compile on newer Linux distributions either, due to the ever-changing tool chain v8 requires/provides.

**Comment by tomvantilburg** [comment]
@robe2 For what it is worth, this person recently went through the pain of (successfully) building a newer V8: https://hackernoon.com/how-to-build-v8-on-windows-and-not-go-mad-6347c69aacd4
I'm still collecting courage to do it myself though after reading his post.

**Comment by JerrySievert** [comment]
I purchased a copy of windows, and am looking to see if it's possible for me to get this beast built.
