### ISSUE TITLE
Pls help,  Build error under ubuntu 18, pg11

### ISSUE THREAD

**Issue by AoAnima** [plv8/plv8#309]
Syncing projects: 100% (22/22), done.              
Running hooks:  17% ( 5/28) clang_format_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/home/ao/plv8/build'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
0> Downloading v8/buildtools/linux64/clang-format...
Downloading 1 files took 81.087668 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' took 81.22 secs
Running hooks:  35% (10/28) gn_linux          
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/home/ao/plv8/build'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 8.658460 second(s)
Running hooks:  39% (11/28) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/home/ao/plv8/build'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 72 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 7.261224 second(s)
Running hooks:  50% (14/28) sysroot_x86    
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/home/ao/plv8/build'
Installing Debian sid i386 root image: /home/ao/plv8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/9e6279438ece6fb42b5333ca90d5e9d0c188a403/debian_sid_i386_sysroot.tar.xz
Hook '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' took 112.25 secs
Running hooks:  57% (16/28) sysroot_x64 
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/home/ao/plv8/build'
Installing Debian sid amd64 root image: /home/ao/plv8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/e7c53f04bd88d29d075bfd1f62b073aeb69cbe09/debian_sid_amd64_sysroot.tar.xz
Hook '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' took 105.85 secs
Running hooks:  71% (20/28) binutils            
________ running '/usr/bin/python v8/third_party/binutils/download.py' in '/home/ao/plv8/build'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
0> Downloading /home/ao/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 18.060219 second(s)
Downloading /home/ao/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /home/ao/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Hook '/usr/bin/python v8/third_party/binutils/download.py' took 19.60 secs
Running hooks:  75% (21/28) clang   
________ running '/usr/bin/python v8/tools/clang/scripts/update.py' in '/home/ao/plv8/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-344066-1.tgz .......... Done.
Hook '/usr/bin/python v8/tools/clang/scripts/update.py' took 130.98 secs
Running hooks: 100% (28/28), done.                  
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Checking out files: 100% (4180/4180), done.
Previous HEAD position was 0405d6ef14 Revert "[parser] Remove RETURN_IF* part 16"
HEAD is now at d481edab15 Version 6.4.388.40
Running depot tools as root is sad.
Syncing projects:  95% (22/23) v8/tools/gyp                             
[0:02:13] Still working on:
[0:02:13]   v8/test/wasm-js

[0:02:23] Still working on:
[0:02:23]   v8/test/wasm-js

[0:02:33] Still working on:
[0:02:33]   v8/test/wasm-js

[0:02:40] Still working on:
[0:02:40]   v8/test/wasm-js
Syncing projects: 100% (23/23), done.         

WARNING: 'v8/third_party/googletest/src' is no longer part of this client.  It is recommended that you manually remove it.

WARNING: 'v8/third_party/depot_tools' is no longer part of this client.  It is recommended that you manually remove it.

WARNING: 'v8/test/wasm-js/data' is no longer part of this client.  It is recommended that you manually remove it.

Running hooks:  17% ( 4/23) clang_format_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/home/ao/plv8/build'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
Running hooks:  39% ( 9/23) luci-go_linux     
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' in '/home/ao/plv8/build'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
0> Downloading v8/tools/luci-go/linux64/isolate...
Downloading 1 files took 27.275271 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' took 27.32 secs
Running hooks:  52% (12/23) gn_linux     
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/home/ao/plv8/build'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 8.120848 second(s)
Running hooks:  56% (13/23) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/home/ao/plv8/build'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Removed v8/test/wasm-spec-tests/tests...
0> Extracting 65 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 6.380354 second(s)
Running hooks:  60% (14/23) closure_compiler
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' in '/home/ao/plv8/build'
NOTICE: You have PROXY values set in your environment, but gsutil in depot_tools does not (yet) obey them.
Also, --no_auth prevents the normal BOTO_CONFIG environment variable from being used.
To use a proxy in this situation, please supply those settings in a .boto file pointed to by the NO_AUTH_BOTO_CONFIG environment var.
0> Downloading v8/src/inspector/build/closure-compiler.tar.gz...
0> Extracting 4 entries from v8/src/inspector/build/closure-compiler.tar.gz to v8/src/inspector/build/closure-compiler
Downloading 1 files took 15.789770 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' took 15.86 secs
Running hooks:  65% (15/23) sysroot         
________ running '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/home/ao/plv8/build'
Installing Debian Stretch amd64 root image: /home/ao/plv8/build/v8/build/linux/debian_stretch_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/2202c161310ffde63729f29d27fe7bb24a0bc540/debian_stretch_amd64_sysroot.tar.xz
Tarball sha1sum is wrong.Expected eb7e2d2c563b6a6f6e32b967d5585a6d33636d35, actual: 6576349f1787f98b367557f17041ddadf64858d6
Error: Command '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' returned non-zero exit status 1 in /home/ao/plv8/build
Hook '/usr/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' took 54.39 secs

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@io.(none)')

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
Makefile:35: recipe for target 'build/v8' failed
make: *** [build/v8] Error 1

**Comment by JerrySievert** [comment]
from your error:

```
*** Please tell me who you are.

Run

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@io.(none)')
```

looks like you don't have `git` set up, and it needs that in order for `git` to work successfully.

**Comment by AoAnima** [comment]
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -shared -o plv8-2.3.8.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/usr/lib/x86_64-linux-gnu  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed  -Lbuild/v8/out.gn/x64.release/obj -Lbuild/v8/out.gn/x64.release/obj/third_party/icu -lv8_base -lv8_snapshot -lv8_libplatform -lv8_libbase -lv8_libsampler -lv8_libplatform -Lbuild/v8/out.gn/x64.release/obj -lrt -std=c++11 -lc++
/usr/bin/ld: cannot find -lc++abi
collect2: error: ld returned 1 exit status
/usr/lib/postgresql/11/lib/pgxs/src/makefiles/../../src/Makefile.shlib:303: recipe for target 'plv8-2.3.8.so' failed
make: *** [plv8-2.3.8.so] Error 1

**Comment by AoAnima** [comment]
And:
$ sudo make
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -shared -o plv8-2.3.8.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/usr/lib/x86_64-linux-gnu  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed  -Lbuild/v8/out.gn/x64.release/obj -Lbuild/v8/out.gn/x64.release/obj/third_party/icu -lv8_base -lv8_snapshot -lv8_libplatform -lv8_libbase -lv8_libsampler -lv8_libplatform -Lbuild/v8/out.gn/x64.release/obj -lrt -std=c++11 -lc++
cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
ninja: no work to do.
mkdir -p upgrade
./generate_upgrade.sh 2.3.8
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plv8 - > plv8.control
sed -e 's/@LANG_NAME@/plv8/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -DLANG_plv8 - > plv8--2.3.8.sql
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plcoffee - > plcoffee.control
sed -e 's/@LANG_NAME@/plcoffee/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -DLANG_plcoffee - > plcoffee--2.3.8.sql
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plls - > plls.control
sed -e 's/@LANG_NAME@/plls/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -DLANG_plls - > plls--2.3.8.sql
make: *** Нет правила для сборки цели «plv8.bc», требуемой для «all».  Ост

**Comment by AoAnima** [comment]
It seems to have happened after I did what is written here: [this](https://github.com/plv8/plv8/issues/304#issuecomment-426035141)  
О вроди бы получилось после того как сделал [Это](https://github.com/plv8/plv8/issues/304#issuecomment-426035141) 
Выложил сюда: [PLV8-Postgresql11-Ubuntu-1](https://github.com/AoAnima/PLV8-Postgresql11-Ubuntu-18)

**Comment by JerrySievert** [comment]
can you verify that you have llvm installed?

**Comment by AoAnima** [comment]
> 
> 
> can you verify that you have llvm installed?

Yes, I'll check on Monday!

**Comment by asah** [comment]
Happening to me as well.  For reproducibility, here's a [Dockerfile].(https://github.com/plv8/plv8/files/2875728/Dockerfile.txt) 

p.s. apologies if this is a v8 compilation issue...


$ sudo docker build .
Sending build context to Docker daemon  99.39MB
Step 1/9 : FROM ubuntu:18.04
Step 2/9 : ARG DEBIAN_FRONTEND=noninteractive
Step 3/9 : RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends     git wget build-essential pkg-config gnupg python
Step 4/9 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
Step 5/9 : RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic"-pgdg main | tee /etc/apt/sources.list.d/pgdg.list
Step 6/9 : RUN apt -y update && apt -y install --no-install-recommends postgresql-11 postgresql-server-dev-11
Step 7/9 : RUN wget -q --no-check-certificate https://github.com/plv8/plv8/archive/v2.3.3.tar.gz -O - | tar zxf -
Step 8/9 : RUN git config --global http.sslVerify false
Step 9/9 : RUN cd plv8-2.3.3 && make
 ---> Running in 6211b6e8c764
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
cd build; fetch v8; cd v8; git checkout 6.4.388.40; gclient sync ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /plv8-2.3.3/build/_gclient_v8_IvVzGq' in '/plv8-2.3.3/build'
Cloning into '/plv8-2.3.3/build/_gclient_v8_IvVzGq'...
remote: Sending approximately 776.41 MiB ...
remote: Counting objects: 7689, done
remote: Finding sources: 100% (29/29)
remote: Total 643798 (delta 516425), reused 643788 (delta 516425)
Receiving objects: 100% (643798/643798), 776.17 MiB | 24.29 MiB/s, done.
...
[0:02:06] Still working on:
[0:02:06]   v8
Error: Command 'cipd ensure -log-level error -root /plv8-2.3.3/build -ensure-file /tmp/tmpfXonFB.ensure' returned non-zero exit status 5
Traceback (most recent call last):
  File "/plv8-2.3.3/build/depot_tools/fetch.py", line 306, in <module>
    sys.exit(main())
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
  File "/plv8-2.3.3/build/depot_tools/fetch.py", line 301, in main
    return run(options, spec, root)
  File "/plv8-2.3.3/build/depot_tools/fetch.py", line 295, in run
    return checkout.init()
  File "/plv8-2.3.3/build/depot_tools/fetch.py", line 137, in init
    self.run_gclient(*sync_cmd)
  File "/plv8-2.3.3/build/depot_tools/fetch.py", line 82, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/plv8-2.3.3/build/depot_tools/fetch.py", line 71, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 1
Previous HEAD position was dbaa5b7b9a [gm.py] Strip carriage returns from mksnapshot arguments
HEAD is now at d481edab15 Version 6.4.388.40

WARNING: 'v8/third_party/googletest/src' is no longer part of this client.  It is recommended that you manually remove it.


WARNING: 'v8/third_party/depot_tools' is no longer part of this client.  It is recommended that you manually remove it.


WARNING: 'v8/test/wasm-js/data' is no longer part of this client.  It is recommended that you manually remove it.

________ running '/usr/bin/python v8/gypfiles/landmines.py' in '/plv8-2.3.3/build'
Clobbering due to missing landmines file.
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/plv8-2.3.3/build'
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /plv8-2.3.3/build
Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format. [Err: /plv8-2.3.3/build/depot_tools/vpython: line 42: /plv8-2.3.3/build/depot_tools/.cipd_bin/vpython: No such file or directory
]
0> Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format, skipping. [Err: /plv8-2.3.3/build/depot_tools/vpython: line 42: /plv8-2.3.3/build/depot_tools/.cipd_bin/vpython: No such file or directory
]
Downloading 1 files took 0.045667 second(s)

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
**subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1**
make: *** [build/v8] Error 1
Makefile:39: recipe for target 'build/v8' failed
The command '/bin/sh -c cd plv8-2.3.3 && make' returned a non-zero code: 2

---

Also, make can't be re-run, which really slows down development...

$ make
cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
ninja: error: loading 'build.ninja': No such file or directory
Makefile:46: recipe for target 'v8' failed
make: *** [v8] Error 1

`make distclean` seems to reset things but requires a 700+MB download and 643808 file git pull - even in google cloud this is pretty slow!

**Comment by JerrySievert** [comment]
it is indeed a v8 compilation issue, but if you can get a shell, you can track down where it is failing and why.

from looking at the errors:

```
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /plv8-2.3.3/build
Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format. [Err: /plv8-2.3.3/build/depot_tools/vpython: line 42: /plv8-2.3.3/build/depot_tools/.cipd_bin/vpython: No such file or directory
]
0> Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format, skipping. [Err: /plv8-2.3.3/build/depot_tools/vpython: line 42: /plv8-2.3.3/build/depot_tools/.cipd_bin/vpython: No such file or directory
]
```

there's a failure downloading v8's build version of python.

I will note that it looks like you're on 2.3.3, I'd recommend going to 2.3.9 instead, as a bit has been changed, including direct support for pg11:

https://github.com/plv8/plv8/blob/v2.3.9/Changes

either way, with a shell, you can follow the same path that plv8 uses to build v8:

https://github.com/plv8/plv8/blob/v2.3.9/Makefile#L39

```
cd build; fetch v8; cd v8; git checkout $(AUTOV8_VERSION); gclient sync ; cd build/config ; git cherry-pick 4287a0d364541583a50cc91465330251460d489a ; cd ../.. ; tools/dev/v8gen.py $(PLATFORM) -- $(V8_OPTIONS)
```

the failure you are seeing is in `fetch v8`.  you can add `build/depot_tools` to your path, and since v8 itself is already checked out, make sure that it's on the correct branch:

```
$ cd v8
$ git checkout 6.4.388.40
$ gclient sync
```

which will begin the download of each of the build prerequisites for v8, and get it ready for build.  since you're not on macOS, you can safely ignore the cherry-pick.

if you see a failure, the errors generally tell you how you can fix them, or get more information.

I will note that a quick google search of `Failed to fetch file gs://chromium-clang-format/5349d1954e17f6ccafb6e6663b0f13cdb2bb33c8 for v8/buildtools/linux64/clang-format` is showing me that likely you're missing `curl` though.

**Comment by PoOwAa** [comment]
I had the same problem today. First I got the git error (I already had git installed, so just quickly configured email and username, but it wasn't the source of error) as well, after that the following error:
```
Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
Makefile:35: recipe for target 'build/v8' failed
make: *** [build/v8] Error 1
```
When I tried to run make again, it gave me the ninja.build error.

the solution for me was to install libc++-dev and libc++abi-dev

```
$ apt install libc++-dev

$ apt install libc++abi-dev
```

Hope it helps anyone else :smile:

**Comment by asah** [comment]
does this help?
https://github.com/plv8/plv8/commit/0ead6b4eb1294f47f5a2a06a0418eee102b0b169
